name: ci

on:
  release:
    types: [published]

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4

      -
        name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: |
            ghcr.io/gheinzer/neontex:latest
            ghcr.io/gheinzer/neontex:${{ github.ref_name }}

  docs:
    runs-on: ubuntu-latest
    needs: docker
    container:
      image: ghcr.io/gheinzer/neontex:latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4

      - name: Build docs
        run: |
          cd docs
          latexmk -xelatex main.tex

      - name: Upload PDF to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: main.pdf
          asset_name: neontex_docs.pdf
          tag: ${{ github.ref }}
          overwrite: true